CalDAV to sync properly when limit is set in PDO backend
sabre-io/dav pull request #1248
Opened 2020-02-16 09:51 UTC by nhirokinet

Hi,

I altered some codes to make CalDAV sync properly even when limit is set. Changes is mainly as below two:

- Return syncToken when limit is set. Current code returns the syncToken of the latest server state. Changed to return the syncToken corresponding to the truncated sync result.
  - When the result limit is designated by client, this is not the consistent as returned result.
  - In [RFC6578 section 3.6](https://tools.ietf.org/html/rfc6578#section-3.6): `the DAV:sync-token value returned in the response MUST represent the correct state for the partial set of
   changes returned.`
  - So, when truncation occurs, client will miss the truncated event even in later sync, since the client receives the syncToken of not received events, and asks server to send the event after that next time.
- When response is truncated, 507 record is added to the response.
  - Defined in [RFC6578 section 3.6](https://tools.ietf.org/html/rfc6578#section-3.6)
  - With this, the client can recognize the result is truncated, and can retry until the client syncs with the latest state.

OneCalendar in Windows Store sends a request with limit 1000, and I checked using this, but with the changes below:

- I defanged the code of Authentication because OneCalendar did not send a request with Digest authentication.
- I overrided the limit to 2 in `lib/CalDAV/Backend/PDO.php` while testing.

I think CardDAV has the same issue, but I did not find an environment to reproduce and test with, so I wrote a code only for CalDAV, PDO backend.

This is my first code around WebDAV, so could you take a look including my understanding is correct or not?

2020-02-16 23:18 UTC, evert commented
It's a bit hard for me to eye this and see if it's correct, but it *looks* good. I feel that this can use a good amount of unittests to ensure that edge cases are sufficiently covered and increase confidence.

2020-02-17 16:08 UTC, nhirokinet commented
I added test case for each of two changes.

2020-03-13 12:02 UTC, nhirokinet commented
@DeepDiver1975 I added some tests after your comments, should I add some more change?

2020-10-17 04:26 UTC, nhirokinet commented
Hi, is there something I can do to advance this pull request?
CI fails, but it seems to be some new timezone test, which this pull request does not touch.

2021-10-16 16:47 UTC, nhirokinet commented
@DeepDiver1975 Hi, do you have some comments about added tests?

2021-12-01 17:51 UTC, nhirokinet commented
@phil-davis @DeepDiver1975 Hi, do you know the status about this? I added some tests according to your comment, long ago, that I'm not sure about my memory, anything more I should do?

2021-12-01 18:25 UTC, DeepDiver1975 requested changes

2021-12-01 18:25 UTC, DeepDiver1975 commented on tests/Sabre/DAV/Sync/PluginTest.php
> +        $this->assertEquals(2, count($responses), 'We expected exactly 1 {DAV:}response');
> We expected exactly 1 {DAV:}response

We expected exactly 2 {DAV:}response

2021-12-01 18:30 UTC, nhirokinet commented on tests/Sabre/DAV/Sync/PluginTest.php
> +        $this->assertEquals(2, count($responses), 'We expected exactly 1 {DAV:}response');
fixed the message.

2021-12-01 18:36 UTC, DeepDiver1975 approved these changes

2021-12-02 04:43 UTC, phil-davis approved these changes

2021-12-02 04:45 UTC, phil-davis commented
Rebased and squashed. LGTM, thanks. Merging.

2021-12-02 04:45 UTC, merged