fix: Handle `Depth` header for `COPY` as this is required by RFC
sabre-io/dav pull request #1495
Opened 2023-10-25 22:12 UTC by susnux

Currently Sabre\DAV does not support the `Depth` header on `COPY` and `MOVE`.
But the RFC4918 requires servers to do so, the header is not required but:

* If the header is missing 'infinity' shall be assumed -> This is how we handle **every** request currently
* For `MOVE` the header, if available, **must** be 'infinity' -> We just have to check the header and throw bad request otherwise
* For `COPY` the header may 'infinity' or a positive integer including 0
  * The depths defines how many levels of children shall be copied
  * If the depth is zero only the collection and its properties are copied, but **not** any children

So especially the `COPY` method is currently broken, we noticed this when using the WebDAV litmus test bench (version 0.14) which checks for shallow copies (meaning copy a collection with depth 0).

This PR fixes all of this points, while trying to keep backwards compatible. Of cause any using application that implements `ICopyTarget::copyInto` is still broken and need to adapt to the depth change (it continues to work as before, but the bug fix does not propagate).

Reference from the RFC:
* The requirement on the server support of `COPY` `Depth` 'infinity' and '0': rfc4918#section-9.8.3
* For `MOVE` only `Depth: infinity` is allowed: rfc4918#section-9.9.2

2023-11-08 15:11 UTC, DeepDiver1975 requested changes

2023-11-08 15:11 UTC, DeepDiver1975 commented on lib/DAV/Server.php
> +        if ($depth !== 'infinity' && is_numeric($depth)) {
In core plugin above it is stated that only `infinity` is allowed. Adding this logic here can reduce the necessary code changes a lot.

2024-02-10 23:50 UTC, susnux commented on lib/DAV/Server.php
> +        if ($depth !== 'infinity' && is_numeric($depth)) {
@DeepDiver1975 yes thats for `MOVE`, but for `COPY` we need to support also numeric values.

2024-04-04 14:14 UTC, susnux commented
ping again, also cc @phil-davis 

Would be great to get this fixed so sabre passes the litmus test v15 ( https://github.com/notroj/litmus previously http://www.webdav.org/neon/litmus/ )

2024-08-13 13:07 UTC, susnux commented
Anything I can help with to get this reviewed? (I do not want to bug you but this would be a great to get fixed :) ).

2024-09-05 09:41 UTC, DeepDiver1975 approved these changes

2024-09-05 09:42 UTC, DeepDiver1975 commented
I miss the ci status - what's going on here?

2024-09-05 09:44 UTC, DeepDiver1975 commented
> I miss the ci status - what's going on here?

@susnux can I ask you to rebase this pull request ... THX

2024-09-05 13:31 UTC, susnux commented
> can I ask you to rebase this pull request ... THX

@DeepDiver1975 sure, done!

2025-01-29 09:39 UTC, susnux commented
Noticed it is still open, is there anything I can help with?

2025-06-26 09:09 UTC, ChristophWurst approved these changes

2025-06-26 09:09 UTC, ChristophWurst commented on lib/DAV/Server.php
> +                throw new Exception\BadRequest('The HTTP Depth header may only be "infinity", 0 or a positiv number');
```suggestion
                throw new Exception\BadRequest('The HTTP Depth header may only be "infinity", 0 or a positive number');
```

2025-06-26 11:36 UTC, kesselb commented
cc @susnux can you rebase, to have a recent ci run?

2025-06-26 11:48 UTC, susnux commented
> can you rebase, to have a recent ci run?

Sure, done

2025-06-26 12:09 UTC, kesselb commented on tests/Sabre/DAV/ServerCopyMoveTest.php
> +        $request = new HTTP\Request('COPY', '/', null !== $headerValue ? ['Depth' => $headerValue] : []);
The test does not work as expected because the destination header is missing. The BadRequest exception is the one for "The destination header was not supplied" and not the invalid depth header.

2025-06-26 12:09 UTC, kesselb commented on tests/Sabre/DAV/ServerCopyMoveTest.php
> +        $this->expectException(BadRequest::class);
```suggestion
        $this->expectException(BadRequest::class);
        $this->expectExceptionMessage('The HTTP Depth header may only be "infinity", 0 or a positive number');
```

2025-06-26 12:09 UTC, kesselb commented on lib/DAV/Server.php
> +        if ('infinity' !== $depth && is_numeric($depth)) {
Test case `2f`: Is not infinity and not numeric => will not enter the block. Is that on purpose, and the parents are supposed to validate if the depth header contains a valid value?

2025-06-26 14:56 UTC, susnux commented on tests/Sabre/DAV/ServerCopyMoveTest.php
> +        $request = new HTTP\Request('COPY', '/', null !== $headerValue ? ['Depth' => $headerValue] : []);
Well yes but there is no test case with a missing header value :sweat_smile: 
I will fix anyways.

2025-06-26 16:22 UTC, susnux commented
@kesselb I pushed a commit solving your comments

2025-10-10 12:54 UTC, susnux commented
@phil-davis anything else to do, to get this PR merged?

2025-11-19 11:04 UTC, alecpl commented on lib/DAV/Server.php
> +            throw new Exception\BadRequest('The HTTP Depth header may only be "infinity", 0 or an positive integer');
"a positive"

2025-11-19 11:04 UTC, alecpl commented on lib/DAV/CorePlugin.php
> +        if (Server::DEPTH_INFINITY !== $moveInfo['depth']) {
I'm not sure this is the best place for this check. When dealing with files `Depth` should be ignored. So, maybe to be on a safe side we should do this check for collections only.

2025-11-19 11:05 UTC, alecpl commented
I just find out about this missing bit. I'd love to see this merged.

2025-11-19 15:43 UTC, susnux commented on lib/DAV/Server.php
> +            throw new Exception\BadRequest('The HTTP Depth header may only be "infinity", 0 or an positive integer');
```suggestion
            throw new Exception\BadRequest('The HTTP Depth header may only be "infinity", 0 or a positive integer');
```

2025-11-19 15:57 UTC, susnux commented on lib/DAV/CorePlugin.php
> +        if (Server::DEPTH_INFINITY !== $moveInfo['depth']) {
For MOVE the RFC is not that explicit but for COPY it is and there we have this part of the RFC:

> Please note, however, that it is always an error to submit a value for the Depth header that is not allowed by the method's definition. Thus submitting a "Depth: 1" on a COPY, even if the resource does not have internal members, will result in a 400 (Bad Request). The method should fail not because the resource doesn't have internal members, but because of the illegal value in the header.

Thus an invalid value of the header has higher priority than the header itself.
So I think throwing here is safe and indicates that the client needs to be fixed.

2025-11-19 16:01 UTC, susnux commented
Rebased to fix the typo in the error message - otherwise no changes.

2025-12-01 20:19 UTC, alecpl approved these changes

2025-12-12 14:59 UTC, provokateurin approved these changes

2025-12-12 15:00 UTC, merged